stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - src/models/model_building.py
    outs:
    - models/model.pkl
  model_eval:
    cmd: python src/models/model_eval.py
    deps:
    - models/model.pkl
    - src/models/model_eval.py
    metrics:
    - reports/metrics.json
  model_registration:
    cmd: python src/model/model_reg.py
    deps:
    - reports/run_info.json
    - src/model/model_reg.py
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
